# Generated by Django 3.2 on 2021-06-08 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOOKING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EMPLOYEE',
            fields=[
                ('CNIC', models.CharField(default='', max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FARE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('Economy', 'ECONOMY'), ('Business', 'BUSINESS'), ('Luxury', 'LUXURY')], max_length=100)),
                ('car_fare', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HOTEL_FARE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_type', models.CharField(choices=[('Two Star', 'TWO STAR'), ('Three Star', 'THREE STAR'), ('Four Star', 'FOUR STAR'), ('Five Star', 'FIVE STAR'), ('Six Star', 'SIX STAR'), ('Seven Star', 'SEVEN STAR')], max_length=100)),
                ('hotel_fare', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hotel Fare',
            },
        ),
        migrations.CreateModel(
            name='TRIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ISLAMABAD', 'ISLAMABAD'), ('RAWALPINDI', 'RAWALPINDI')], max_length=100)),
                ('destination', models.CharField(choices=[('MURREE', 'MURREE'), ('NATHIA GALI', 'NATHIA GALI'), ('NARAN KAGHAN', 'NARAN KAGHAN'), ('KASHMIR', 'KASHMIR'), ('SAWAT', 'SAWAT')], max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TICKET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.PositiveIntegerField(default=0)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.booking')),
            ],
        ),
        migrations.CreateModel(
            name='INVOICE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_charges', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('paid_amount', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='agency.booking')),
            ],
        ),
        migrations.CreateModel(
            name='HOTEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('ISLAMABAD', 'ISLAMABAD'), ('MURREE', 'MURREE'), ('NATHIA GALI', 'NATHIA GALI'), ('NARAN KAGHAN', 'NARAN KAGHAN'), ('KASHMIR', 'KASHMIR'), ('SAWAT', 'SAWAT')], max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default_hotel.jpeg', upload_to='hotel_pics')),
                ('available', models.BooleanField(default=True)),
                ('charges', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.hotel_fare')),
            ],
        ),
        migrations.CreateModel(
            name='FIXED_TRIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ISLAMABAD', 'ISLAMABAD'), ('RAWALPINDI', 'RAWALPINDI')], max_length=100)),
                ('destination', models.CharField(choices=[('MURREE', 'MURREE'), ('NATHIA GALI', 'NATHIA GALI'), ('NARAN KAGHAN', 'NARAN KAGHAN'), ('KASHMIR', 'KASHMIR'), ('SAWAT', 'SAWAT')], max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('available_seats', models.PositiveIntegerField(choices=[(25, 25), (50, 50), (75, 75), (100, 100)])),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('allocated_hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.hotel')),
            ],
            options={
                'verbose_name': 'Fixed Trip',
            },
        ),
        migrations.CreateModel(
            name='FIXED_INVOICE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_charges', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='agency.booking')),
            ],
        ),
        migrations.CreateModel(
            name='FIXED_BOOKING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='agency.fixed_trip')),
            ],
        ),
        migrations.CreateModel(
            name='CAR',
            fields=[
                ('reg_no', models.CharField(default='', max_length=25, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default_car.png', upload_to='car_pics')),
                ('available', models.BooleanField(default=True)),
                ('fare', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.fare')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='allocated_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.car'),
        ),
        migrations.AddField(
            model_name='booking',
            name='allocated_hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='agency.trip'),
        ),
    ]
