# Generated by Django 3.2 on 2021-06-12 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixed_booking',
            name='booking_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fixed_invoice',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixed_invoice',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixed_invoice',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='agency.fixed_booking'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
