# Generated by Django 3.2 on 2021-04-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DRIVER',
            new_name='EMPLOYEE',
        ),
    ]
