# Generated by Django 3.2 on 2021-06-12 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20210612_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixed_booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency.fixed_trip'),
        ),
    ]
