# Generated by Django 3.2 on 2021-04-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_rename_driver_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
