# Generated by Django 3.2 on 2021-05-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_employee_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOOKING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FARE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('Economy', 'ECONOMY'), ('Business', 'BUSINESS'), ('Luxury', 'LUXURY')], max_length=100)),
                ('car_fare', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TRIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ISLAMABAD', 'ISLAMABAD'), ('MURREE', 'MURREE'), ('NATHIA GALI', 'NATHIA GALI'), ('NARAN KAGHAN', 'NARAN KAGHAN'), ('KASHMIR', 'KASHMIR'), ('SAWAT', 'SAWAT')], max_length=100)),
                ('destination', models.CharField(choices=[('ISLAMABAD', 'ISLAMABAD'), ('MURREE', 'MURREE'), ('NATHIA GALI', 'NATHIA GALI'), ('NARAN KAGHAN', 'NARAN KAGHAN'), ('KASHMIR', 'KASHMIR'), ('SAWAT', 'SAWAT')], max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TICKET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.PositiveIntegerField(default=0)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.booking')),
            ],
        ),
        migrations.CreateModel(
            name='CAR',
            fields=[
                ('reg_no', models.CharField(default='', max_length=25, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default_car.png', upload_to='car_pics')),
                ('available', models.BooleanField(default=True)),
                ('fare', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.fare')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='allocated_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.car'),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='agency.trip'),
        ),
    ]
