# Generated by Django 3.2 on 2021-05-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_employee_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOTEL_FARE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_type', models.CharField(choices=[('Two Star', 'TWO STAR'), ('Three Star', 'THREE STAR'), ('Four Star', 'FOUR STAR'), ('Five Star', 'FIVE STAR'), ('Six Star', 'SIX STAR'), ('Seven Star', 'SEVEN STAR')], max_length=100)),
                ('hotel_fare', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HOTEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('ISLAMABAD', 'ISLAMABAD'), ('MURREE', 'MURREE'), ('NATHIA GALI', 'NATHIA GALI'), ('NARAN KAGHAN', 'NARAN KAGHAN'), ('KASHMIR', 'KASHMIR'), ('SAWAT', 'SAWAT')], max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default_hotel.jpeg', upload_to='hotel_pics')),
                ('charges', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.hotel_fare')),
            ],
        ),
    ]
