# Generated by Django 3.2 on 2021-05-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_hotel_hotel_fare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel_fare',
            options={'verbose_name': 'HOTEL_FARE'},
        ),
    ]
