# Generated by Django 3.2 on 2021-05-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20210522_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
