# Generated by Django 3.2 on 2021-05-22 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_alter_hotel_fare_options'),
        ('agency', '0005_trip_is_custom'),
    ]

    operations = [
    ]
