# Generated by Django 3.2 on 2021-05-22 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_merge_20210523_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel_fare',
            options={'verbose_name': 'Hotel Fare'},
        ),
    ]
