# Generated by Django 3.2 on 2021-05-23 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0009_booking_allocated_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(choices=[('MURREE', 'MURREE'), ('NATHIA GALI', 'NATHIA GALI'), ('NARAN KAGHAN', 'NARAN KAGHAN'), ('KASHMIR', 'KASHMIR'), ('SAWAT', 'SAWAT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='source',
            field=models.CharField(choices=[('ISLAMABAD', 'ISLAMABAD'), ('RAWALPINDI', 'RAWALPINDI')], max_length=100),
        ),
        migrations.CreateModel(
            name='FIXED_BOOKING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.hotel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='agency.trip')),
            ],
        ),
    ]
