# Generated by Django 3.2 on 2021-05-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_auto_20210523_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='is_custom',
        ),
    ]
