# Generated by Django 3.2 on 2021-05-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_alter_fixed_trip_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fixed_trip',
            name='available_seats',
            field=models.PositiveIntegerField(choices=[(25, 25), (50, 50), (75, 75), (100, 100)]),
        ),
    ]
